### ISSUE TITLE
Demarshal problem when using @appendable and types evolve

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/OpenDDS#2946]
I have an application v1 that uses the following IDL type

```
module DDS_Native
{
  typedef string<128> color_type;
  @nested(FALSE)
  @appendable
  struct ShapeType {
    @key color_type color;
    long x;
    long y;
    long shapesize;
  };
}; // module DDS_Native
```

Now this application evolves into v2 which uses uses the following IDL definition which is the same type but with an additional field

```
module DDS_Native
{
  typedef string<128> color_type;
  @nested(FALSE)
  @appendable
  struct ShapeType {
    @key color_type color;
    long x;
    long y;
    long shapesize;
    long angle;
  };
}; // module DDS_Native
```

When application v2 publishes a sample v1 does receive the data, the `angle` is just dropped. But when v1 publishes a sample than v2 receives the following error:
```
(17330|17339) ERROR DDS_Native::ShapeTypeDataReaderImpl::dds_demarshal deserialization failed, dropping sample.
```

[openddslog.txt](https://github.com/objectcomputing/OpenDDS/files/7060593/openddslog.txt)

**Comment by jwillemsen** [comment]
This issue was not fixed, see attached log, when having v1 published v2 can't demarshal it, even with the fixes of #3040 

[extensibility_20211003.log](https://github.com/objectcomputing/OpenDDS/files/7272949/extensibility_20211003.log)

**Comment by jwillemsen** [comment]
[extensibliy_transportlogging_20211003.log](https://github.com/objectcomputing/OpenDDS/files/7272954/extensibliy_transportlogging_20211003.log)

**Comment by jwillemsen** [comment]
Full log

[extensibliy_transportlogging_20211003.log](https://github.com/objectcomputing/OpenDDS/files/7272961/extensibliy_transportlogging_20211003.log)

**Comment by jwillemsen** [comment]
Looks we still get unaligned CDR, anything special we should do in our settings?

```
(8948|8948) DataReaderImpl::setup_deserialization: Setup successfully with the following data representations: Unaligned CDR
```

**Comment by mitza-oci** [comment]
Is the new configuration option from #3040 enabled?

**Comment by jwillemsen** [comment]
> Is the new configuration option from #3040 enabled?

We only set RTPS as discovery (see https://github.com/RemedyIT/ciaox11/blob/1e3347656694c1899773752cb196cfe4b7527d11/ddsx11/vendors/opendds/dds/opendds_specific.cpp#L74), so we need to explicitly enable this? We leave the exact transports to be used up to OpenDDS, we don't really care at the ddsx11 level. We do explicitly tag all IDL types with `@appendable`, not sure why we also have to configure the transports with some special settings, doesn't feel logical.

Is there a global option to enable cdr_encapsulation for all transports?

**Comment by mitza-oci** [comment]
There are more details on #3040 about why it's set up this way.  At least for the near term it needs a configuration switch.

However, I thought about it some more and I think this "encapsualtion header" is unnecessary to get Mutable/Appendable support in the non-rtps transports.  The DataSampleHeader and DataRepresentationQosPolicy should be sufficient to get the same info.  

If this turns out to be correct, we should be able to get the same functionality without needing explicit configuration.

**Comment by iguessthislldo** [comment]
> The DataSampleHeader and DataRepresentationQosPolicy should be sufficient to get the same info.

It could depending on the situation, but it's a lot safer to use `EncapsulationHeader` to actually read what the stream says it is to the get the `Encoding` object.

**Comment by jwillemsen** [comment]
We do generate explicit @appendable in the DDS related IDL. Wasn't aware of the missing xcdr2 support for wireshark.

What about a feature to force XCDR2 for all transports at compile time? We generate the OpenDDS configuration we need as part of the AXCIOMA configure process. For our users we force them to use XCDR2, at the moment they need wireshark they have to sponsor something additionally

**Comment by ClaytonCalabrese** [comment]
PR 3135 has been merged in.  If a DataRepresentation is specified in the DataWriter/DataReader QoS for a non rtps_udp transport, it should now enable cdr encapsulation.

Unfortunately due to backwards compatibility, the default representation for non rtps_udp transports will remain `UNALIGNED_CDR`, so both the writer and reader will need to explicitly set their `representation` QoS on these transports.

The configuration option from the previous PR has been removed as it was clunky and is no longer needed.

Additionally, the test case you provided to us has been added as a scenario in the XTypes test.

**Comment by jwillemsen** [comment]
Ok, great, looks we need also https://github.com/objectcomputing/OpenDDS/issues/2434, we only set QoS through XML.

**Comment by mitza-oci** [comment]
> both the writer and reader will need to explicitly set their `representation` QoS on these transports.

Isn't the reader default essentially "accept whatever the writer wrote"?

**Comment by ClaytonCalabrese** [comment]
> > both the writer and reader will need to explicitly set their `representation` QoS on these transports.
> 
> Isn't the reader default essentially "accept whatever the writer wrote"?

No, because we set a different default from the XTypes spec to allow backwards compatibility for users of UnalignedCDR.

The spec states that the default for both writers and readers is and empty set interpreted as XCDR1.

Due to the technical limitations of XCDR1, our interpretation is as follows:

Writer - XCDR2
Reader - a set containing both XCDR2 and XCDR1

However, this was only for rtps_udp transport. For other transports such as tcp, we interpret the empty set as UnalignedCDR for both the writer and reader. If I remember correctly this was the compromise we made to make sure users had access to backwards compatibility with pre-xtypes OpenDDS versions. 

As a result, if we explicitly set XCDR2 as the representation of our writer, but left our reader blank, we would fail to associate because writer (XCDR2) and reader (UnalignedCDR) have no compatible representations.

I think the best compromise here would be to further stray from the spec and  interpret the empty set of representations for ALL transports to be (XCDR2, XCDR1, and UnalignedCDR).  If we did that then a user would only need to set the writer representation QoS.  It would also reduce the weirdness where we have for different behavior for different transports, which, I'm not a fan of.

I would then need to check the code for any places with special handling in the reader and defer to whatever the writer specified, assuming proper checking was done on the writer side.  An exception to this would be checking for XCDR1 mutable, which is an OpenDDS design gap, and so an outside writer would not be doing this check.

**Comment by jwillemsen** [comment]
For our AXCIOMA DDS4CCM extensibility test we still have to force XCDR2, we can now do that uses QoS XML, but preferable we wouldn't need to set it all as user.

**Comment by mitza-oci** [comment]
@jwillemsen can this one be closed?

**Comment by jwillemsen** [comment]
Not to my idea, the user is still forced to set xcdr2 in his qos setting, that shouldn’t be done to my idea when the user uses explicit appendable in his idl

**Comment by jrw972** [comment]
Closing since the original issue is solved.

@jwillemsen Please create a new issue or issues to document your remaining concerns.
