### ISSUE TITLE
Building debian package with cmake build system

### ISSUE THREAD

**Issue by tmayoff** [OpenDDS/OpenDDS#4381]
I've been maintaining a private debian package for work and wanted to switch it to use the cmake build. I get that it's still very early in the cmake support, but it builds much faster (at least with ninja backend) so I'd like to start using it everywhere. 

I added the files to my fork [here](https://github.com/tmayoff/OpenDDS/tree/debian/debian).

 I'm getting some errors,

using this `debuild -us -uc -i` command to build the package
```
'/usr/bin/perl' '/home/tyler/src/OpenDDS/cmake/scrape_gnuace.pl' '--workspace' '/home/tyler/src/OpenDDS/obj-x86_64-linux-gnu/ace_tao' '--loc-base' '/home/tyler/src/OpenDDS/obj-x86_64-linux-gnu' '--ace' '/home/tyler/src/OpenDDS/obj-x86_64-linux-gnu/ace_tao' '--tao' '/home/tyler/src/OpenDDS/obj-x86_64-linux-gnu/ace_tao/TAO'
make[2]:Leaving directory '/home/tyler/src/OpenDDS/obj-x86_64-linux-gnu/ace_tao'
 is missing dir at /home/tyler/src/OpenDDS/cmake/scrape_gnuace.pl line 121.
CMake Error at cmake/build_ace_tao.cmake:39 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 255"

Call Stack (most recent call first):
  CMakeLists.txt:47 (include)
```

I'm not sure if this a cmake, debuild or OpenDDS issue but I wasn't even able to download ace_tao without this flag `-DFETCHCONTENT_FULLY_DISCONNECTED=OFF`.

Any help would be appreciated, also side note, would it be useful to merge the debian package support upstream?

**Comment by iguessthislldo** [comment]
>  is missing dir at /home/tyler/src/OpenDDS/cmake/scrape_gnuace.pl line 121.

`scrape_gnuace` looks like it got confused by something in the ACE/TAO Makefile project listing because it [should be saying what the project name is](https://github.com/OpenDDS/OpenDDS/blob/d3ba55b2db69bef715b7b05ffc2e3d3d9ec790a6/cmake/scrape_gnuace.pl#L121), but it's blank. Can you upload `/home/tyler/src/OpenDDS/obj-x86_64-linux-gnu/ace_tao/GNUmakefile` as an attachment of a comment?

Here is some background on what this script is doing: We can't build ACE/TAO with CMake right now, but we still wanted CMake to mimic the `configure` script and not have the user do completely separate ACE/TAO build. So it's trying to scrap target info from the ACE/TAO Makefiles so CMake can configure OpenDDS without ACE/TAO being build yet. You can do a separate ACE/TAO build and avoid this issue, but then you'd have to configure ACE/TAO manually.
 
> I'm not sure if this a cmake, debuild or OpenDDS issue but I wasn't even able to download ace_tao without this flag -DFETCHCONTENT_FULLY_DISCONNECTED=OFF.

What is it saying exactly? `-DFETCHCONTENT_QUIET=FALSE` might provide more insight if you haven't already tried that.

> would it be useful to merge the debian package support upstream?

So far our approach to any packaging has been that it should be separate from OpenDDS itself. This is why [my own Debian package](https://github.com/iguessthislldo/OpenDDS-Debian) and [Arch User Repo](https://aur.archlinux.org/packages/opendds) were never merged into OpenDDS itself. I don't think this is set in stone though, but should probably be a subject of its own discussion. I haven't reviewed your packaging yet, but if it's further along than mine, I personally wouldn't mind using it as a basis of a separate repo in the OpenDDS org.

Another thing to consider is [CPack](https://cmake.org/cmake/help/latest/module/CPack.html). I haven't had time to explore it fully, but I did make sure it builds at least some sort of package that looks usable. In theory at least it should be able to provide packaging for Debian and more without much work on our part.

**Comment by tmayoff** [comment]
This also happens, when trying to compile OpenDDS as a meson subproject, using the [cmake module](https://mesonbuild.com/CMake-module.html) (it's probably a niche use case)

**Comment by mitza-oci** [comment]
I tried using the GNUmakefile you posted with scrape_gnuace.pl but I didn't get the same error.
Would you please run both of these commands in the directory that has the GNUmakefile and post the output:
`make -f GNUmakefile project_name_list`
`make -f GNUmakefile -npRrq :`
These are the two processes that scrape_gnuace spawns and reads their stdout.

**Comment by tmayoff** [comment]
I have to manually set the ACE_ROOT (which makes sense the variables are coming from cmake)
```
ACE_ROOT=./ make -f GNUmakefile project_name_list
ACE
TAO_IDL_BE
TAO_IDL_BE_VIS_A
TAO_IDL_BE_VIS_C
TAO_IDL_BE_VIS_E
TAO_IDL_BE_VIS_I
TAO_IDL_BE_VIS_O
TAO_IDL_BE_VIS_S
TAO_IDL_BE_VIS_U
TAO_IDL_BE_VIS_V
TAO_IDL_EXE
TAO_IDL_FE
Svc_Utils
AnyTypeCode
AnyTypeCode_Idl
BiDir_GIOP
BiDir_GIOP_Idl
CSD_Framework
CSD_Framework_Idl
CSD_ThreadPool
CodecFactory
CodecFactory_Idl
Codeset
Codeset_Idl
DynamicInterface
TAO-target
TAO_Core_idl
IORManipulation
IORManipulation_Idl
Async_IORTable
Async_IORTable_Core_Idl
IORTable
IORTable_Core_Idl
ImR_Client
ImR_Client_Idl
Messaging
Messaging_Idl
PI
PI_Idl
PortableServer
PortableServer_Idl
Valuetype
Valuetype_Idl
gperf
```

`make -f GNUmakefile -npRrq :`
[out.txt](https://github.com/OpenDDS/OpenDDS/files/13905155/out.txt)


Also forgive if me if this is total nonsense, but trying to debug the perl script I edited line 121 like so
```
die("PROJECT: $project->{name} is missing dir") if (!defined($project->{dir}));
```
and rerunning I get
```
PROJECT: make[1]:Entering directory '/home/jayne/src/module-GC/build/subprojects/opendds/__CMake_build/ace_tao'
| is missing dir at /home/jayne/src/module-GC/subprojects/opendds/cmake/scrape_gnuace.pl line 121.
```

Which wouldn't that mean the variable in $project->{name} is in fact the make cmd, meaning get_projects() isn't parsing the output correctly? Could it be that debuild and meson are setting env vars or something to run make verbosely
