### ISSUE TITLE
Build Failed -  Missing DdsDcpsCoreTypeSupport.idl

### ISSUE THREAD

**Issue by amielc1** [OpenDDS/OpenDDS#4674]
I  use [Building and Installing](https://opendds.readthedocs.io/en/latest-release/devguide/building/index.html) guide to build RtpsRelay.
i used `configure` with security flag 
`configure --security --openssl=%VCPKG_INSTALL% --xerces3=%VCPKG_INSTALL%` 
when I build I fail because :

`40>C:\Users\amielc\Downloads\install\OpenDDS\OpenDDS-3.28.1\ace_wrappers\bin\tao_idl : error : Unable to open file (stat) "DdsDcpsCoreTypeSupport.idl": No such file or directory`

this is my environments variables :

`$env:ACE_ROOT = "C:\Users\amielc\Downloads\install\OpenDDS\OpenDDS-3.28.1\ace_wrappers"
$env:TAO_ROOT = "$env:ACE_ROOT\TAO"
$env:DDS_ROOT = "C:\Users\amielc\Downloads\install\OpenDDS\OpenDDS-3.28.1"
$env:PATH = "$env:ACE_ROOT\bin;$env:DDS_ROOT\bin;$env:PATH"`

some idl's doesn't exist : 
![Snag_fbe6985](https://github.com/OpenDDS/OpenDDS/assets/2409265/72a6c8b2-37c0-4fb1-9fcf-93370c49cbca)
[OpenddsBuildOutput.txt](https://github.com/user-attachments/files/15587026/OpenddsBuildOutput.txt)

**Comment by mitza-oci** [comment]
From the log: "40>------ Rebuild All started: Project: OpenDDS_Dcps, Configuration: Debug x64 ------"
Do not use "Rebuild All" in Visual Studio.  Just build the solution.  If you need to clean it, that's a separate step.

**Comment by amielc1** [comment]
@mitza-oci thank you, 
can you please tell me the steps to build? 
Do I have to start all over? (configure, setenv .. etc .. ) ?

**Comment by mitza-oci** [comment]
Use the "Build Solution" command in Visual Studio, or equivalent on the command line with msbuild or devenv.
At this point I don't think you will need to start over.

https://opendds.readthedocs.io/en/latest-release/devguide/quickstart/windows.html

**Comment by amielc1** [comment]
@mitza-oci I Built it again - still, its doesn't pass 
[openDdsAmielBuild.txt](https://github.com/user-attachments/files/15595617/openDdsAmielBuild.txt)

**Comment by mitza-oci** [comment]
I'm not sure why that didn't work.  Try running this from the Visual Studio Command Prompt that has the OpenDDS environment variables set up:

```
cd %DDS_ROOT%\dds
..\bin\opendds_idl DdsDcpsCore.idl
```

It should create 3 files in the same directory (see file names below).  Check that these are present with the current timestamp.  Then delete them since they shouldn't be used  -- we didn't run opendds_idl with all the other command-line arguments that build uses.

```
DdsDcpsCoreTypeSupportImpl.h
DdsDcpsCoreTypeSupport.idl
DdsDcpsCoreTypeSupportImpl.cpp
```

If this simple test is working and your build is not, it's probably time to start over from scratch.  The steps described here and in the documentation are essentially what OpenDDS maintainers use for local development and the GitHub Actions CI uses.

**Comment by amielc1** [comment]
@mitza-oci 
 ` Build succeeded` ` Build succeeded` ` Build succeeded` ` Build succeeded`
My mistake was: that after I did `setenv` command - I opened VS manually and not from the command line (with devenv command) .
MUST:  avoid starting VS manually, because environment variables would be deleted.

**Comment by mitza-oci** [comment]
That makes sense, thanks for the update.
